import type { SystemId } from "../lib/anatomy-data";

/**
 * Strings added for the Systems browser, saved organs, study notes, the guided
 * lesson flow, model error states and quiz progression.
 *
 * These live in one locale-keyed file rather than being spread across the
 * `ui/<locale>.ts` dictionaries: the set is cohesive, was added in one go, and
 * keeping it together means a missing translation is visible in a single diff.
 * The type makes every locale mandatory, so the build fails on drift.
 */
export type ExtraUi = {
  systems: { title: string; names: Record<SystemId, string> };
  saved: { title: string; empty: string; add: string; remove: string };
  notes: { title: string; placeholder: string; status: string };
  search: { empty: string; clear: string };
  lesson: {
    step: string; next: string; back: string; finish: string;
    overview: string; structures: string; clinical: string; sources: string; sourcesIntro: string;
  };
  related: { title: string };
  viewer: { error: string; retry: string; hint: string; previous: string; next: string };
  quiz: { best: string; newBest: string; mastery: string; review: string; reviewCount: string; modeIdentify: string; modeReverse: string; modeDescribe: string; reversePrompt: string; optionsLabel: string };
  /** Kid-mode copy: the grown-ups panel and child-facing progress wording. */
  kids: { grownups: string; grownupsTitle: string; grownupsIntro: string; privacy: string; conditionsTitle: string; conditionsIntro: string; partsKnown: string; practice: string; practiceCount: string; amazingFacts: string; howItWorks: string };
  /** "See it in your room" — the AR sheet and its in-camera overlay. */
  ar: { button: string; title: string; introWebxr: string; introQuickLook: string; preparing: string; start: string; lifeSize: string; enlarged: string; unsupported: string; failed: string; placeHint: string; placed: string; done: string; safety: string };
  /** Question of the day and the streak. */
  daily: { tab: string; title: string; whichOrgan: string; whichPart: string; correct: string; wrong: string; streakLabel: string; streakStart: string; best: string; comeBack: string; see3d: string; newQuestion: string };
  /** The sticker book: the child-facing view of progress. */
  stickers: { button: string; title: string; count: string; gold: string; howTo: string; locked: string; newSticker: string; newGold: string; organDone: string; tapHint: string };
  /** "Feel your heartbeat": the camera pulse reading. */
  heartbeat: { button: string; title: string; intro: string; privacy: string; fun: string; start: string; cover: string; hold: string; live: string; result: string; challenge: string; watch: string; again: string; stop: string; noCamera: string; noPulse: string; beating: string };
  /** Read-aloud button (shown only when the device has a voice for the locale). */
  speech: { read: string; stop: string };
};

export const extra: Record<string, ExtraUi> = {
  en: {
    systems: { title: "Body systems", names: { cardiovascular: "Cardiovascular", nervous: "Nervous", respiratory: "Respiratory", digestive: "Digestive", urinary: "Urinary", sensory: "Sensory", endocrine: "Endocrine", integumentary: "Integumentary" } },
    saved: { title: "Saved organs", empty: "No saved organs yet. Use the bookmark to keep one here.", add: "Save this organ", remove: "Remove from saved" },
    notes: { title: "Study notes", placeholder: "Write what you want to remember about the {organ}…", status: "Saved on this device" },
    search: { empty: "No organs match “{query}”.", clear: "Clear search" },
    lesson: { step: "Step {current} of {total}", next: "Next", back: "Back", finish: "Finish lesson", overview: "Overview", structures: "Structures to find", clinical: "Why it matters clinically", sources: "Sources", sourcesIntro: "This lesson draws on the following references." },
    related: { title: "Related organs" },
    viewer: { error: "The {organ} model could not be loaded.", retry: "Try again", hint: "Use the arrow keys to step through structures.", previous: "Previous structure", next: "Next structure" },
    quiz: { best: "Best: {score}/{total}", newBest: "New personal best!", mastery: "Mastery {percent}%", review: "Review", reviewCount: "{count} due for review", modeIdentify: "Find the", modeReverse: "Name highlighted", modeDescribe: "Match the description", reversePrompt: "What is highlighted?", optionsLabel: "Answer choices" },
    kids: { grownups: "Grown-ups", grownupsTitle: "For grown-ups", grownupsIntro: "Anatomy Atelier helps curious kids explore the body. It’s a learning tool, not medical advice — if you’re worried about your child’s health, talk to a doctor.", privacy: "Progress and notes are saved only in this browser, on this device. There are no accounts.", conditionsTitle: "Health conditions linked to the {organ}", conditionsIntro: "These aren’t shown on your child’s screens. They’re here so you can talk about them together if they come up.", partsKnown: "You know {count} of {total} body parts", practice: "Practice time!", practiceCount: "Body parts to practice: {count}", amazingFacts: "Amazing facts", howItWorks: "How it works" },
    ar: { button: "See it in your room", title: "The {organ} in your room", introWebxr: "Point your camera at a table or the floor, then tap to place the {organ}. Walk around it to see every side.", introQuickLook: "Your device will open the {organ} in its AR viewer. Point at a table or the floor to place it.", preparing: "Getting the {organ} ready…", start: "Place it in my room", lifeSize: "Life size: about {size} cm", enlarged: "Enlarged so you can see it better", unsupported: "Open Anatomy Atelier on a phone or tablet to put the {organ} in your room.", failed: "AR couldn’t start on this device. You can still explore the {organ} here.", placeHint: "Move your phone slowly until you see the ring, then tap", placed: "Tap somewhere else to move it", done: "Done", safety: "Stay somewhere safe and watch where you walk." },
    daily: { tab: "Today", title: "Question of the day", whichOrgan: "Which organ is this?", whichPart: "Which part of the {organ} is this?", correct: "Yes! That’s right.", wrong: "Good try! It’s the {answer}.", streakLabel: "Day streak", streakStart: "Answer today to start your streak!", best: "Best: {count}", comeBack: "Come back tomorrow for a new question.", see3d: "See it in 3D", newQuestion: "A new question is waiting" },
    stickers: { button: "My sticker book", title: "My sticker book", count: "{count} of {total} stickers", gold: "{count} gold", howTo: "Answer a quiz question right to earn a sticker. Keep getting it right over a few days to make it gold!", locked: "Not found yet", newSticker: "New sticker!", newGold: "Gold sticker!", organDone: "You found every part of the {organ}!", tapHint: "Tap a sticker to find it in 3D." },
    heartbeat: { button: "Feel your heartbeat", title: "Your heartbeat", intro: "Your phone’s camera can see your pulse! Gently cover the back camera with your fingertip and hold still for about 15 seconds.", privacy: "The camera only checks the colour of your fingertip. No pictures are saved or sent anywhere.", fun: "Just for fun — this isn’t a medical test.", start: "Start", cover: "Cover the camera with your fingertip", hold: "Hold still…", live: "{bpm} beats a minute", result: "Your heart is beating about {bpm} times a minute!", challenge: "Try 20 jumping jacks, then measure again. What changes?", watch: "Watch the 3D heart beat with you", again: "Measure again", stop: "Stop", noCamera: "We couldn’t use the camera. A grown-up can allow camera access in the browser settings.", noPulse: "We couldn’t find your pulse. Press more gently, keep very still, and try near a bright lamp.", beating: "Beating with you: {bpm} a minute" },
    speech: { read: "Read aloud", stop: "Stop reading" },
  },
  xh: {
    systems: { title: "Iinkqubo zomzimba", names: { cardiovascular: "Intliziyo negazi", nervous: "Imithambo-luvo", respiratory: "Ukuphefumla", digestive: "Ukwetyisa", urinary: "Umchamo", sensory: "Izivamvo", endocrine: "Iihomoni", integumentary: "Ulusu" } },
    saved: { title: "Amalungu agciniweyo", empty: "Akukho malungu agciniweyo okwangoku. Sebenzisa ibhukhmakhi ukugcina elinye apha.", add: "Gcina eli lungu", remove: "Susa kwagciniweyo" },
    notes: { title: "Amanqaku okufunda", placeholder: "Bhala into ofuna ukuyikhumbula: {organ}…", status: "Kugcinwe kwesi sixhobo" },
    search: { empty: "Akukho lungu lihambelana no-“{query}”.", clear: "Cima ukhangelo" },
    lesson: { step: "Inyathelo {current} / {total}", next: "Okulandelayo", back: "Buyela umva", finish: "Gqiba isifundo", overview: "Isishwankathelo", structures: "Amalungu ekufuneka uwafumene", clinical: "Kutheni kubalulekile kwezonyango", sources: "Imithombo", sourcesIntro: "Esi sifundo sisekelwe kule mithombo ilandelayo." },
    related: { title: "Amalungu anxulumeneyo" },
    viewer: { error: "Imodeli ayikwazanga ukulayishwa: {organ}.", retry: "Zama kwakhona", hint: "Sebenzisa amaqhosha otolo ukuhamba phakathi kwamalungu.", previous: "Ilungu elidlulileyo", next: "Ilungu elilandelayo" },
    quiz: { best: "Awona manqaku: {score}/{total}", newBest: "Irekhodi entsha!", mastery: "Ubuchule {percent}%", review: "Phinda ujonge", reviewCount: "Ekufuneka ziphinde zijongwe: {count}", modeIdentify: "Fumana", modeReverse: "Biza igama lelo liphawuliweyo", modeDescribe: "Hambelanisa inkcazelo", reversePrompt: "Yintoni ephawuliweyo?", optionsLabel: "Iimpendulo onokukhetha kuzo" },
    kids: { grownups: "Abantu abadala", grownupsTitle: "Kubantu abadala", grownupsIntro: "I-Anatomy Atelier inceda abantwana abanomdla ukuba baphonononge umzimba. Sisixhobo sokufunda, asiyongcebiso yezonyango — ukuba unexhala ngempilo yomntwana wakho, thetha nogqirha.", privacy: "Inkqubela namanqaku agcinwa kule bhrawuza kuphela, kwesi sixhobo. Akukho ziakhawunti.", conditionsTitle: "Izifo ezinxulumene: {organ}", conditionsIntro: "Ezi azibonakali kwizikrini zomntwana wakho. Zikhona apha ukuze nithethe ngazo kunye ukuba ziye zavela.", partsKnown: "Amalungu omzimba owaziyo: {count}/{total}", practice: "Ixesha lokuziqhelisa!", practiceCount: "Amalungu okuziqhelisa: {count}", amazingFacts: "Iinyani ezimangalisayo", howItWorks: "Isebenza njani" },
    ar: { button: "Yibone egumbini lakho", title: "Egumbini lakho: {organ}", introWebxr: "Jolisa ikhamera yakho etafileni okanye emgangathweni, emva koko ucofe ukuze ubeke: {organ}. Hamba ujikeleze ukuze ubone onke amacala.", introQuickLook: "Isixhobo sakho siza kuvula kwisiboniso se-AR: {organ}. Jolisa etafileni okanye emgangathweni ukuze uyibeke.", preparing: "Kulungiselelwa: {organ}…", start: "Yibeke egumbini lam", lifeSize: "Ubukhulu bokwenyani: malunga ne-{size} cm", enlarged: "Yandisiwe ukuze uyibone kakuhle", unsupported: "Vula i-Anatomy Atelier kwifowuni okanye kwithebhulethi ukuze ubeke egumbini lakho: {organ}.", failed: "I-AR ayikwazanga ukuqala kwesi sixhobo. Usenako ukuphonononga apha: {organ}.", placeHint: "Hambisa ifowuni yakho kancinci de ubone iringi, emva koko ucofe", placed: "Cofa kwenye indawo ukuze uyishukumise", done: "Kugqityiwe", safety: "Hlala kwindawo ekhuselekileyo kwaye ujonge apho uhamba khona." },
    daily: { tab: "Namhlanje", title: "Umbuzo wosuku", whichOrgan: "Leliphi ilungu lomzimba eli?", whichPart: "{organ}: yeyiphi inxalenye le?", correct: "Ewe! Uchanile.", wrong: "Uzamile kakuhle! Impendulo: {answer}.", streakLabel: "Iintsuku zilandelelana", streakStart: "Phendula namhlanje ukuze uqalise uthotho lwakho!", best: "Eyona: {count}", comeBack: "Buya ngomso ufumane umbuzo omtsha.", "see3d": "Yibone kwi-3D", newQuestion: "Umbuzo omtsha ulindile" },
    stickers: { button: "Incwadi yam yezitikha", title: "Incwadi yam yezitikha", count: "Izitikha: {count}/{total}", gold: "Zegolide: {count}", howTo: "Phendula umbuzo ngokuchanekileyo ukuze ufumane isitikha. Qhubeka uchanile kangangeentsuku ezimbalwa ukuze sibe yigolide!", locked: "Asikafunyanwa", newSticker: "Isitikha esitsha!", newGold: "Isitikha segolide!", organDone: "Uwafumene onke amalungu: {organ}!", tapHint: "Cofa isitikha ukuze usifumane kwi-3D." },
    heartbeat: { button: "Yiva ukubetha kwentliziyo yakho", title: "Ukubetha kwentliziyo yakho", intro: "Ikhamera yefowuni yakho iyakwazi ukubona ipulse yakho! Gquma ikhamera yangasemva kancinci ngencam yomnwe wakho uze uhlale uzolile malunga nemizuzwana eli-15.", privacy: "Ikhamera ijonga kuphela umbala wencam yomnwe wakho. Akukho mifanekiso igcinwayo okanye ithunyelwe naphi na.", fun: "Kukuzonwabisa nje — ayilovavanyo lwezonyango.", start: "Qala", cover: "Gquma ikhamera ngencam yomnwe wakho", hold: "Hlala uzolile…", live: "{bpm} ngomzuzu", result: "Intliziyo yakho ibetha malunga ne-{bpm} ngomzuzu!", challenge: "Yenza ii-jumping jacks ezingama-20, uze ulinganise kwakhona. Yintoni etshintshayo?", watch: "Bukela intliziyo ye-3D ibetha nawe", again: "Linganisa kwakhona", stop: "Yima", noCamera: "Asikwazanga ukusebenzisa ikhamera. Umntu omdala angavumela ikhamera kuseto lwebhrawuza.", noPulse: "Asiyifumananga ipulse yakho. Cinezela kancinci, uhlale uzolile kakhulu, uzame kufutshane nesibane esikhanyayo.", beating: "Ibetha nawe: {bpm} ngomzuzu" },
    speech: { read: "Ndifundele", stop: "Yeka ukufunda" },
  },
  zu: {
    systems: { title: "Izinhlelo zomzimba", names: { cardiovascular: "Inhliziyo negazi", nervous: "Izinzwa", respiratory: "Ukuphefumula", digestive: "Ukugaya ukudla", urinary: "Umchamo", sensory: "Ukuzwa", endocrine: "Amahomoni", integumentary: "Isikhumba" } },
    saved: { title: "Izitho ezigciniwe", empty: "Azikho izitho ezigciniwe okwamanje. Sebenzisa ibhukhimakhi ukugcina esinye lapha.", add: "Gcina lesi sitho", remove: "Susa kwezigciniwe" },
    notes: { title: "Amanothi okufunda", placeholder: "Bhala okufuna ukukukhumbula: {organ}…", status: "Kugcinwe kule divayisi" },
    search: { empty: "Asikho isitho esifana no-“{query}”.", clear: "Sula usesho" },
    lesson: { step: "Isinyathelo {current} / {total}", next: "Okulandelayo", back: "Emuva", finish: "Qeda isifundo", overview: "Ukubuka konke", structures: "Izingxenye okufanele uzithole", clinical: "Kungani kubalulekile kwezempilo", sources: "Imithombo", sourcesIntro: "Lesi sifundo sisekelwe kule mithombo elandelayo." },
    related: { title: "Izitho ezihlobene" },
    viewer: { error: "Imodeli ayikwazanga ukulayishwa: {organ}.", retry: "Zama futhi", hint: "Sebenzisa izinkinobho zemicibisholo ukuhamba phakathi kwezingxenye.", previous: "Ingxenye edlule", next: "Ingxenye elandelayo" },
    quiz: { best: "Okuphezulu: {score}/{total}", newBest: "Irekhodi elisha!", mastery: "Ubuchule {percent}%", review: "Buyekeza", reviewCount: "Okufanele kubuyekezwe: {count}", modeIdentify: "Thola", modeReverse: "Qamba igama lokugqanyisiwe", modeDescribe: "Fanisa incazelo", reversePrompt: "Yini egqanyisiwe?", optionsLabel: "Izimpendulo ongakhetha kuzo" },
    kids: { grownups: "Abantu abadala", grownupsTitle: "Kwabantu abadala", grownupsIntro: "I-Anatomy Atelier isiza izingane ezinelukuluku ukuthi zihlole umzimba. Iyithuluzi lokufunda, hhayi iseluleko sezempilo — uma ukhathazekile ngempilo yengane yakho, khuluma nodokotela.", privacy: "Inqubekela phambili namanothi kugcinwa kule bhrawuza kuphela, kule divayisi. Awekho ama-akhawunti.", conditionsTitle: "Izifo ezihlobene: {organ}", conditionsIntro: "Lokhu akuboniswa ezikrinini zengane yakho. Kulapha ukuze nikhulume ngakho ndawonye uma kuvela.", partsKnown: "Izingxenye zomzimba ozaziyo: {count}/{total}", practice: "Isikhathi sokuzijwayeza!", practiceCount: "Izingxenye zokuzijwayeza: {count}", amazingFacts: "Amaqiniso amangalisayo", howItWorks: "Isebenza kanjani" },
    ar: { button: "Yibone ekamelweni lakho", title: "Ekamelweni lakho: {organ}", introWebxr: "Khomba ikhamera yakho etafuleni noma phansi, bese uthepha ukuze ubeke: {organ}. Hamba uzungeze ukuze ubone zonke izinhlangothi.", introQuickLook: "Idivayisi yakho izovula esibukelini se-AR: {organ}. Khomba etafuleni noma phansi ukuze uyibeke.", preparing: "Kulungiselelwa: {organ}…", start: "Yibeke ekamelweni lami", lifeSize: "Ubukhulu bangempela: cishe u-{size} cm", enlarged: "Ikhulisiwe ukuze uyibone kangcono", unsupported: "Vula i-Anatomy Atelier efonini noma kuthebhulethi ukuze ubeke ekamelweni lakho: {organ}.", failed: "I-AR ayikwazanga ukuqala kule divayisi. Usengahlola lapha: {organ}.", placeHint: "Hambisa ifoni yakho kancane uze ubone indandatho, bese uthepha", placed: "Thepha kwenye indawo ukuze uyihambise", done: "Kuqediwe", safety: "Hlala endaweni ephephile futhi ubheke lapho uhamba khona." },
    daily: { tab: "Namuhla", title: "Umbuzo wosuku", whichOrgan: "Yisiphi isitho lesi?", whichPart: "{organ}: yiyiphi ingxenye le?", correct: "Yebo! Kulungile.", wrong: "Uzame kahle! Impendulo: {answer}.", streakLabel: "Izinsuku zilandelana", streakStart: "Phendula namuhla ukuze uqale uchungechunge lwakho!", best: "Okuphezulu: {count}", comeBack: "Buya kusasa uthole umbuzo omusha.", "see3d": "Yibone ku-3D", newQuestion: "Umbuzo omusha ulindile" },
    stickers: { button: "Incwadi yami yezitikha", title: "Incwadi yami yezitikha", count: "Izitikha: {count}/{total}", gold: "Ezegolide: {count}", howTo: "Phendula umbuzo kahle ukuze uthole isitikha. Qhubeka uphendula kahle izinsuku ezimbalwa ukuze sibe segolide!", locked: "Akukatholakali", newSticker: "Isitikha esisha!", newGold: "Isitikha segolide!", organDone: "Uzitholile zonke izingxenye: {organ}!", tapHint: "Thepha isitikha ukuze usithole ku-3D." },
    heartbeat: { button: "Zwa ukushaya kwenhliziyo yakho", title: "Ukushaya kwenhliziyo yakho", intro: "Ikhamera yefoni yakho ingabona ukushaya kwemithambo yakho! Mboza ikhamera yangemuva kancane ngesihloko somunwe wakho bese uhlala unganyakazi cishe imizuzwana eyi-15.", privacy: "Ikhamera ibheka kuphela umbala wesihloko somunwe wakho. Azikho izithombe ezigcinwayo noma ezithunyelwa ndawo.", fun: "Kungokuzijabulisa nje — akusona isivivinyo sezempilo.", start: "Qala", cover: "Mboza ikhamera ngesihloko somunwe wakho", hold: "Unganyakazi…", live: "{bpm} ngomzuzu", result: "Inhliziyo yakho ishaya cishe izikhathi ezingu-{bpm} ngomzuzu!", challenge: "Yenza ama-jumping jacks angu-20, bese ukala futhi. Yini eshintshayo?", watch: "Buka inhliziyo ye-3D ishaya nawe", again: "Kala futhi", stop: "Misa", noCamera: "Asikwazanga ukusebenzisa ikhamera. Umuntu omdala angavumela ikhamera kuzilungiselelo zebhrawuza.", noPulse: "Asikutholanga ukushaya kwemithambo yakho. Cindezela kancane, unganyakazi nhlobo, bese uzama eduze kwelambu elikhanyayo.", beating: "Ishaya nawe: {bpm} ngomzuzu" },
    speech: { read: "Ngifundele", stop: "Misa ukufunda" },
  },
  af: {
    systems: { title: "Liggaamstelsels", names: { cardiovascular: "Bloedsomloop", nervous: "Senuwee", respiratory: "Asemhaling", digestive: "Spysvertering", urinary: "Urinêr", sensory: "Sintuie", endocrine: "Hormone", integumentary: "Vel" } },
    saved: { title: "Gestoorde organe", empty: "Nog geen gestoorde organe nie. Gebruik die boekmerk om een hier te hou.", add: "Stoor hierdie orgaan", remove: "Verwyder uit gestoorde" },
    notes: { title: "Studienotas", placeholder: "Skryf wat jy oor die {organ} wil onthou…", status: "Op hierdie toestel gestoor" },
    search: { empty: "Geen organe pas by “{query}” nie.", clear: "Maak soektog skoon" },
    lesson: { step: "Stap {current} van {total}", next: "Volgende", back: "Terug", finish: "Voltooi les", overview: "Oorsig", structures: "Dele om te vind", clinical: "Waarom dit klinies saak maak", sources: "Bronne", sourcesIntro: "Hierdie les steun op die volgende bronne." },
    related: { title: "Verwante organe" },
    viewer: { error: "Die {organ}-model kon nie gelaai word nie.", retry: "Probeer weer", hint: "Gebruik die pyltjiesleutels om deur die dele te gaan.", previous: "Vorige deel", next: "Volgende deel" },
    quiz: { best: "Beste: {score}/{total}", newBest: "Nuwe persoonlike beste!", mastery: "Bemeestering {percent}%", review: "Hersien", reviewCount: "Om te hersien: {count}", modeIdentify: "Vind die", modeReverse: "Noem die gemerkte deel", modeDescribe: "Pas die beskrywing", reversePrompt: "Wat is gemerk?", optionsLabel: "Antwoordkeuses" },
    kids: { grownups: "Grootmense", grownupsTitle: "Vir grootmense", grownupsIntro: "Anatomy Atelier help nuuskierige kinders om die liggaam te verken. Dit is ’n leerhulpmiddel, nie mediese advies nie — as jy bekommerd is oor jou kind se gesondheid, praat met ’n dokter.", privacy: "Vordering en notas word net in hierdie blaaier, op hierdie toestel, gestoor. Daar is geen rekeninge nie.", conditionsTitle: "Gesondheidstoestande verbonde aan die {organ}", conditionsIntro: "Dit word nie op jou kind se skerms gewys nie. Dit is hier sodat julle saam daaroor kan praat as dit ter sprake kom.", partsKnown: "Jy ken {count} van {total} liggaamsdele", practice: "Oefentyd!", practiceCount: "Liggaamsdele om te oefen: {count}", amazingFacts: "Wonderlike feite", howItWorks: "Hoe dit werk" },
    ar: { button: "Sien dit in jou kamer", title: "Die {organ} in jou kamer", introWebxr: "Rig jou kamera op ’n tafel of die vloer, en tik dan om die {organ} neer te sit. Loop om dit om elke kant te sien.", introQuickLook: "Jou toestel sal die {organ} in sy AR-kyker oopmaak. Rig op ’n tafel of die vloer om dit neer te sit.", preparing: "Die {organ} word gereed gemaak…", start: "Sit dit in my kamer", lifeSize: "Ware grootte: omtrent {size} cm", enlarged: "Vergroot sodat jy dit beter kan sien", unsupported: "Maak Anatomy Atelier op ’n foon of tablet oop om die {organ} in jou kamer te sit.", failed: "AR kon nie op hierdie toestel begin nie. Jy kan steeds die {organ} hier verken.", placeHint: "Beweeg jou foon stadig totdat jy die ring sien, en tik dan", placed: "Tik êrens anders om dit te skuif", done: "Klaar", safety: "Bly op ’n veilige plek en kyk waar jy loop." },
    daily: { tab: "Vandag", title: "Vraag van die dag", whichOrgan: "Watter orgaan is dit?", whichPart: "Watter deel van die {organ} is dit?", correct: "Ja! Dis reg.", wrong: "Goeie poging! Dis die {answer}.", streakLabel: "Dae aaneen", streakStart: "Antwoord vandag om jou reeks te begin!", best: "Beste: {count}", comeBack: "Kom môre terug vir ’n nuwe vraag.", "see3d": "Sien dit in 3D", newQuestion: "’n Nuwe vraag wag" },
    stickers: { button: "My plakkerboek", title: "My plakkerboek", count: "{count} van {total} plakkers", gold: "{count} goud", howTo: "Antwoord ’n vasvravraag reg om ’n plakker te verdien. Hou aan om dit oor ’n paar dae reg te kry om dit goud te maak!", locked: "Nog nie gevind nie", newSticker: "Nuwe plakker!", newGold: "Goue plakker!", organDone: "Jy het elke deel van die {organ} gevind!", tapHint: "Tik op ’n plakker om dit in 3D te vind." },
    heartbeat: { button: "Voel jou hartklop", title: "Jou hartklop", intro: "Jou foon se kamera kan jou polsslag sien! Bedek die agterste kamera saggies met jou vingerpunt en hou omtrent 15 sekondes stil.", privacy: "Die kamera kyk net na die kleur van jou vingerpunt. Geen foto’s word gestoor of iewers heen gestuur nie.", fun: "Net vir die pret — dit is nie ’n mediese toets nie.", start: "Begin", cover: "Bedek die kamera met jou vingerpunt", hold: "Hou stil…", live: "{bpm} slae per minuut", result: "Jou hart klop omtrent {bpm} keer per minuut!", challenge: "Doen 20 sterspronge en meet dan weer. Wat verander?", watch: "Kyk hoe die 3D-hart saam met jou klop", again: "Meet weer", stop: "Stop", noCamera: "Ons kon nie die kamera gebruik nie. ’n Grootmens kan kameratoegang in die blaaierinstellings toelaat.", noPulse: "Ons kon nie jou polsslag vind nie. Druk saggies, bly baie stil, en probeer naby ’n helder lamp.", beating: "Klop saam met jou: {bpm} per minuut" },
    speech: { read: "Lees hardop", stop: "Hou op lees" },
  },
};
