import type { SystemId } from "../lib/anatomy-data";

/**
 * Strings added for the Systems browser, saved organs, study notes, the guided
 * lesson flow, model error states and quiz progression.
 *
 * These live in one locale-keyed file rather than being spread across the 12
 * `ui/<locale>.ts` dictionaries: the set is cohesive, was added in one go, and
 * keeping it together means a missing translation is visible in a single diff.
 * The type makes every locale mandatory, so the build fails on drift.
 */
export type ExtraUi = {
  systems: { title: string; names: Record<SystemId, string> };
  saved: { title: string; empty: string; add: string; remove: string };
  notes: { title: string; placeholder: string; status: string };
  search: { empty: string; clear: string };
  lesson: {
    step: string; next: string; back: string; finish: string;
    overview: string; structures: string; clinical: string; sources: string; sourcesIntro: string;
  };
  related: { title: string };
  viewer: { error: string; retry: string; hint: string; previous: string; next: string };
  quiz: { best: string; newBest: string; mastery: string; review: string; reviewCount: string; modeIdentify: string; modeReverse: string; modeDescribe: string; reversePrompt: string; optionsLabel: string };
  /** Kid-mode copy: the grown-ups panel and child-facing progress wording. */
  kids: { grownups: string; grownupsTitle: string; grownupsIntro: string; privacy: string; conditionsTitle: string; conditionsIntro: string; partsKnown: string; practice: string; practiceCount: string; amazingFacts: string; howItWorks: string };
  /** "See it in your room" — the AR sheet and its in-camera overlay. */
  ar: { button: string; title: string; introWebxr: string; introQuickLook: string; preparing: string; start: string; lifeSize: string; enlarged: string; unsupported: string; failed: string; placeHint: string; placed: string; done: string; safety: string };
  /** Question of the day and the streak. */
  daily: { tab: string; title: string; whichOrgan: string; whichPart: string; correct: string; wrong: string; streakLabel: string; streakStart: string; best: string; comeBack: string; see3d: string; newQuestion: string };
};

export const extra: Record<string, ExtraUi> = {
  en: {
    systems: { title: "Body systems", names: { cardiovascular: "Cardiovascular", nervous: "Nervous", respiratory: "Respiratory", digestive: "Digestive", urinary: "Urinary", sensory: "Sensory", endocrine: "Endocrine", integumentary: "Integumentary" } },
    saved: { title: "Saved organs", empty: "No saved organs yet. Use the bookmark to keep one here.", add: "Save this organ", remove: "Remove from saved" },
    notes: { title: "Study notes", placeholder: "Write what you want to remember about the {organ}…", status: "Saved on this device" },
    search: { empty: "No organs match “{query}”.", clear: "Clear search" },
    lesson: { step: "Step {current} of {total}", next: "Next", back: "Back", finish: "Finish lesson", overview: "Overview", structures: "Structures to find", clinical: "Why it matters clinically", sources: "Sources", sourcesIntro: "This lesson draws on the following references." },
    related: { title: "Related organs" },
    viewer: { error: "The {organ} model could not be loaded.", retry: "Try again", hint: "Use the arrow keys to step through structures.", previous: "Previous structure", next: "Next structure" },
    quiz: { best: "Best: {score}/{total}", newBest: "New personal best!", mastery: "Mastery {percent}%", review: "Review", reviewCount: "{count} due for review", modeIdentify: "Find the", modeReverse: "Name highlighted", modeDescribe: "Match the description", reversePrompt: "What is highlighted?", optionsLabel: "Answer choices" },
    kids: { grownups: "Grown-ups", grownupsTitle: "For grown-ups", grownupsIntro: "Anatomy Atelier helps curious kids explore the body. It’s a learning tool, not medical advice — if you’re worried about your child’s health, talk to a doctor.", privacy: "Progress and notes are saved only in this browser, on this device. There are no accounts.", conditionsTitle: "Health conditions linked to the {organ}", conditionsIntro: "These aren’t shown on your child’s screens. They’re here so you can talk about them together if they come up.", partsKnown: "You know {count} of {total} body parts", practice: "Practice time!", practiceCount: "{count} body parts to practice", amazingFacts: "Amazing facts", howItWorks: "How it works" },
    ar: { button: "See it in your room", title: "The {organ} in your room", introWebxr: "Point your camera at a table or the floor, then tap to place the {organ}. Walk around it to see every side.", introQuickLook: "Your device will open the {organ} in its AR viewer. Point at a table or the floor to place it.", preparing: "Getting the {organ} ready…", start: "Place it in my room", lifeSize: "Life size: about {size} cm", enlarged: "Enlarged so you can see it better", unsupported: "Open Anatomy Atelier on a phone or tablet to put the {organ} in your room.", failed: "AR couldn’t start on this device. You can still explore the {organ} here.", placeHint: "Move your phone slowly until you see the ring, then tap", placed: "Tap somewhere else to move it", done: "Done", safety: "Stay somewhere safe and watch where you walk." },
    daily: { tab: "Today", title: "Question of the day", whichOrgan: "Which organ is this?", whichPart: "Which part of the {organ} is this?", correct: "Yes! That’s right.", wrong: "Good try! It’s the {answer}.", streakLabel: "Day streak", streakStart: "Answer today to start your streak!", best: "Best: {count}", comeBack: "Come back tomorrow for a new question.", see3d: "See it in 3D", newQuestion: "A new question is waiting" },
  },
  es: {
    systems: { title: "Sistemas del cuerpo", names: { cardiovascular: "Cardiovascular", nervous: "Nervioso", respiratory: "Respiratorio", digestive: "Digestivo", urinary: "Urinario", sensory: "Sensorial", endocrine: "Endocrino", integumentary: "Tegumentario" } },
    saved: { title: "Órganos guardados", empty: "Aún no hay órganos guardados. Usa el marcador para guardar uno aquí.", add: "Guardar este órgano", remove: "Quitar de guardados" },
    notes: { title: "Notas de estudio", placeholder: "Escribe lo que quieras recordar sobre el {organ}…", status: "Guardado en este dispositivo" },
    search: { empty: "Ningún órgano coincide con «{query}».", clear: "Borrar búsqueda" },
    lesson: { step: "Paso {current} de {total}", next: "Siguiente", back: "Atrás", finish: "Finalizar lección", overview: "Resumen", structures: "Estructuras a localizar", clinical: "Por qué importa clínicamente", sources: "Fuentes", sourcesIntro: "Esta lección se basa en las siguientes referencias." },
    related: { title: "Órganos relacionados" },
    viewer: { error: "No se pudo cargar el modelo del {organ}.", retry: "Reintentar", hint: "Usa las flechas para recorrer las estructuras.", previous: "Estructura anterior", next: "Estructura siguiente" },
    quiz: { best: "Mejor: {score}/{total}", newBest: "¡Nuevo récord personal!", mastery: "Dominio {percent}%", review: "Repasar", reviewCount: "{count} pendientes de repaso", modeIdentify: "Encuentra", modeReverse: "Nombra la estructura resaltada", modeDescribe: "Relaciona la descripción", reversePrompt: "¿Qué está resaltado?", optionsLabel: "Opciones de respuesta" },
    kids: { grownups: "Adultos", grownupsTitle: "Para adultos", grownupsIntro: "Anatomy Atelier ayuda a los niños curiosos a explorar el cuerpo. Es una herramienta de aprendizaje, no un consejo médico: si te preocupa la salud de tu hijo o hija, habla con un médico.", privacy: "El progreso y las notas se guardan solo en este navegador, en este dispositivo. No hay cuentas.", conditionsTitle: "{organ}: problemas de salud relacionados", conditionsIntro: "No aparecen en las pantallas de tu hijo o hija. Están aquí para que puedan hablar de ellos juntos si surgen.", partsKnown: "Conoces {count} de {total} partes del cuerpo", practice: "¡Hora de practicar!", practiceCount: "{count} partes del cuerpo para practicar", amazingFacts: "Datos asombrosos", howItWorks: "Cómo funciona" },
    ar: { button: "Míralo en tu habitación", title: "{organ} en tu habitación", introWebxr: "Apunta la cámara a una mesa o al suelo y toca para colocar: {organ}. Camina alrededor para mirar desde todos los lados.", introQuickLook: "Tu dispositivo abrirá {organ} en su visor de RA. Apunta a una mesa o al suelo.", preparing: "Preparando: {organ}…", start: "Colocar en mi habitación", lifeSize: "Tamaño real: unos {size} cm", enlarged: "Ampliado para verse mejor", unsupported: "Abre Anatomy Atelier en un teléfono o una tableta para poner {organ} en tu habitación.", failed: "La RA no pudo iniciarse en este dispositivo. Puedes seguir explorando aquí: {organ}.", placeHint: "Mueve el teléfono despacio hasta ver el anillo y luego toca", placed: "Toca en otro lugar para mover el modelo", done: "Listo", safety: "Quédate en un lugar seguro y mira por dónde caminas." },
    daily: { tab: "Hoy", title: "Pregunta del día", whichOrgan: "¿Qué órgano es este?", whichPart: "{organ}: ¿qué parte es esta?", correct: "¡Sí! Correcto.", wrong: "¡Buen intento! Es: {answer}.", streakLabel: "Racha", streakStart: "¡Responde hoy para empezar tu racha!", best: "Récord: {count}", comeBack: "Vuelve mañana para una nueva pregunta.", see3d: "Verlo en 3D", newQuestion: "Te espera una pregunta nueva" },
  },
  hi: {
    systems: { title: "शरीर तंत्र", names: { cardiovascular: "हृदय-संवहनी", nervous: "तंत्रिका", respiratory: "श्वसन", digestive: "पाचन", urinary: "मूत्र", sensory: "संवेदी", endocrine: "अंतःस्रावी", integumentary: "त्वचा" } },
    saved: { title: "सहेजे गए अंग", empty: "अभी कोई अंग सहेजा नहीं गया। बुकमार्क से यहाँ जोड़ें।", add: "इस अंग को सहेजें", remove: "सहेजे गए से हटाएँ" },
    notes: { title: "अध्ययन नोट्स", placeholder: "{organ} के बारे में जो याद रखना है वह लिखें…", status: "इस डिवाइस पर सहेजा गया" },
    search: { empty: "“{query}” से कोई अंग मेल नहीं खाता।", clear: "खोज साफ़ करें" },
    lesson: { step: "चरण {current} / {total}", next: "आगे", back: "पीछे", finish: "पाठ समाप्त करें", overview: "अवलोकन", structures: "खोजने योग्य संरचनाएँ", clinical: "नैदानिक महत्व", sources: "स्रोत", sourcesIntro: "यह पाठ निम्नलिखित संदर्भों पर आधारित है।" },
    related: { title: "संबंधित अंग" },
    viewer: { error: "{organ} का मॉडल लोड नहीं हो सका।", retry: "फिर प्रयास करें", hint: "संरचनाओं में जाने के लिए तीर कुंजियाँ दबाएँ।", previous: "पिछली संरचना", next: "अगली संरचना" },
    quiz: { best: "सर्वश्रेष्ठ: {score}/{total}", newBest: "नया व्यक्तिगत रिकॉर्ड!", mastery: "दक्षता {percent}%", review: "दोहराव", reviewCount: "{count} दोहराने बाकी", modeIdentify: "ढूँढें", modeReverse: "हाइलाइट की गई संरचना का नाम बताएं", modeDescribe: "विवरण से मिलाएँ", reversePrompt: "क्या हाइलाइट किया गया है?", optionsLabel: "उत्तर विकल्प" },
    kids: { grownups: "बड़ों के लिए", grownupsTitle: "बड़ों के लिए", grownupsIntro: "Anatomy Atelier जिज्ञासु बच्चों को शरीर को जानने में मदद करता है। यह सीखने का साधन है, चिकित्सा सलाह नहीं — अगर आपको अपने बच्चे के स्वास्थ्य की चिंता है, तो डॉक्टर से बात करें।", privacy: "प्रगति और नोट्स केवल इसी ब्राउज़र में, इसी डिवाइस पर सहेजे जाते हैं। कोई खाता नहीं है।", conditionsTitle: "{organ}: संबंधित स्वास्थ्य समस्याएँ", conditionsIntro: "ये आपके बच्चे की स्क्रीन पर नहीं दिखतीं। ये यहाँ हैं ताकि ज़रूरत पड़ने पर आप साथ बैठकर इनके बारे में बात कर सकें।", partsKnown: "तुम्हें शरीर के {total} में से {count} हिस्से पता हैं", practice: "अभ्यास का समय!", practiceCount: "अभ्यास के लिए {count} हिस्से", amazingFacts: "कमाल के तथ्य", howItWorks: "यह कैसे काम करता है" },
    ar: { button: "अपने कमरे में देखो", title: "तुम्हारे कमरे में: {organ}", introWebxr: "कैमरे को मेज़ या फ़र्श की ओर करो, फिर {organ} रखने के लिए टैप करो। हर तरफ़ से देखने के लिए उसके चारों ओर घूमो।", introQuickLook: "तुम्हारा डिवाइस AR व्यूअर में {organ} खोलेगा। उसे रखने के लिए मेज़ या फ़र्श की ओर करो।", preparing: "तैयारी हो रही है: {organ}…", start: "मेरे कमरे में रखो", lifeSize: "असली आकार: लगभग {size} सेमी", enlarged: "बेहतर देखने के लिए बड़ा दिखाया गया", unsupported: "{organ} को अपने कमरे में रखने के लिए Anatomy Atelier को फ़ोन या टैबलेट पर खोलो।", failed: "इस डिवाइस पर AR शुरू नहीं हो सका। तुम यहाँ {organ} को देखना जारी रख सकते हो।", placeHint: "रिंग दिखने तक फ़ोन को धीरे-धीरे घुमाओ, फिर टैप करो", placed: "इसे हटाने के लिए कहीं और टैप करो", done: "हो गया", safety: "सुरक्षित जगह पर रहो और देखकर चलो।" },
    daily: { tab: "आज", title: "आज का सवाल", whichOrgan: "यह कौन-सा अंग है?", whichPart: "{organ}: यह कौन-सा हिस्सा है?", correct: "हाँ! बिल्कुल सही।", wrong: "अच्छी कोशिश! सही जवाब: {answer}।", streakLabel: "लगातार दिन", streakStart: "सिलसिला शुरू करने के लिए आज जवाब दो!", best: "सबसे ज़्यादा: {count}", comeBack: "नए सवाल के लिए कल फिर आना।", see3d: "3D में देखो", newQuestion: "एक नया सवाल तुम्हारा इंतज़ार कर रहा है" },
  },
  zh: {
    systems: { title: "人体系统", names: { cardiovascular: "心血管系统", nervous: "神经系统", respiratory: "呼吸系统", digestive: "消化系统", urinary: "泌尿系统", sensory: "感觉系统", endocrine: "内分泌系统", integumentary: "皮肤系统" } },
    saved: { title: "已收藏器官", empty: "尚未收藏器官。点击书签图标即可收藏。", add: "收藏此器官", remove: "取消收藏" },
    notes: { title: "学习笔记", placeholder: "写下你想记住的关于{organ}的内容……", status: "已保存在本设备" },
    search: { empty: "没有与“{query}”匹配的器官。", clear: "清除搜索" },
    lesson: { step: "第 {current} 步，共 {total} 步", next: "下一步", back: "上一步", finish: "完成课程", overview: "概述", structures: "需要辨认的结构", clinical: "临床意义", sources: "资料来源", sourcesIntro: "本课程参考了以下资料。" },
    related: { title: "相关器官" },
    viewer: { error: "无法加载{organ}模型。", retry: "重试", hint: "使用方向键逐个查看结构。", previous: "上一个结构", next: "下一个结构" },
    quiz: { best: "最佳：{score}/{total}", newBest: "创造了个人最佳！", mastery: "掌握度 {percent}%", review: "复习", reviewCount: "{count} 项待复习", modeIdentify: "找到", modeReverse: "说出高亮结构", modeDescribe: "匹配描述", reversePrompt: "高亮的是什么？", optionsLabel: "答案选项" },
    kids: { grownups: "家长", grownupsTitle: "给家长", grownupsIntro: "Anatomy Atelier 帮助好奇的孩子探索人体。它是学习工具，不是医疗建议——如果您担心孩子的健康，请咨询医生。", privacy: "学习进度和笔记只保存在此设备的这个浏览器中。无需注册账号。", conditionsTitle: "{organ}：相关的健康问题", conditionsIntro: "这些内容不会出现在孩子的界面上。放在这里，是为了在孩子问起时，您可以和孩子一起聊聊。", partsKnown: "你已认识 {total} 个身体部位中的 {count} 个", practice: "练习时间到！", practiceCount: "{count} 个身体部位待练习", amazingFacts: "神奇的知识", howItWorks: "它是怎样工作的" },
    ar: { button: "放到你的房间里看看", title: "房间里的{organ}", introWebxr: "把摄像头对准桌子或地面，然后轻点放下{organ}。绕着它走一圈，从各个角度看看。", introQuickLook: "你的设备会在 AR 查看器中打开{organ}。对准桌子或地面就能放下它。", preparing: "正在准备{organ}…", start: "放到我的房间里", lifeSize: "真实大小：约 {size} 厘米", enlarged: "已放大，方便你看清楚", unsupported: "在手机或平板上打开 Anatomy Atelier，就能把{organ}放到你的房间里。", failed: "这台设备无法启动 AR。你仍然可以在这里探索{organ}。", placeHint: "慢慢移动手机，直到看见圆环，然后轻点", placed: "轻点其他地方可以移动它", done: "完成", safety: "待在安全的地方，走路时注意脚下。" },
    daily: { tab: "今天", title: "每日一问", whichOrgan: "这是哪个器官？", whichPart: "{organ}：这是哪个部分？", correct: "对啦！答对了。", wrong: "很棒的尝试！答案是：{answer}。", streakLabel: "连续天数", streakStart: "今天回答，开始你的连续记录吧！", best: "最高纪录：{count}", comeBack: "明天再来回答新问题吧。", see3d: "看 3D 模型", newQuestion: "有一个新问题在等你" },
  },
  ar: {
    systems: { title: "أجهزة الجسم", names: { cardiovascular: "القلب والأوعية", nervous: "العصبي", respiratory: "التنفسي", digestive: "الهضمي", urinary: "البولي", sensory: "الحسي", endocrine: "الغدد الصماء", integumentary: "الجلدي" } },
    saved: { title: "الأعضاء المحفوظة", empty: "لا توجد أعضاء محفوظة بعد. استخدم الإشارة المرجعية لحفظ عضو هنا.", add: "احفظ هذا العضو", remove: "إزالة من المحفوظات" },
    notes: { title: "ملاحظات الدراسة", placeholder: "اكتب ما تريد تذكره عن {organ}…", status: "محفوظ على هذا الجهاز" },
    search: { empty: "لا يوجد عضو يطابق «{query}».", clear: "مسح البحث" },
    lesson: { step: "الخطوة {current} من {total}", next: "التالي", back: "السابق", finish: "إنهاء الدرس", overview: "نظرة عامة", structures: "التراكيب المطلوب تحديدها", clinical: "الأهمية السريرية", sources: "المصادر", sourcesIntro: "يستند هذا الدرس إلى المراجع التالية." },
    related: { title: "أعضاء ذات صلة" },
    viewer: { error: "تعذّر تحميل نموذج {organ}.", retry: "إعادة المحاولة", hint: "استخدم مفاتيح الأسهم للتنقل بين التراكيب.", previous: "التركيب السابق", next: "التركيب التالي" },
    quiz: { best: "الأفضل: {score}/{total}", newBest: "رقم شخصي جديد!", mastery: "الإتقان {percent}٪", review: "مراجعة", reviewCount: "{count} بانتظار المراجعة", modeIdentify: "حدّد", modeReverse: "سمِّ التركيب المميز", modeDescribe: "طابق الوصف", reversePrompt: "ما التركيب المميز؟", optionsLabel: "خيارات الإجابة" },
    kids: { grownups: "للكبار", grownupsTitle: "للكبار", grownupsIntro: "يساعد Anatomy Atelier الأطفال الفضوليين على استكشاف الجسم. إنه أداة تعليمية وليس استشارة طبية — إذا كنت قلقًا بشأن صحة طفلك، فتحدّث إلى طبيب.", privacy: "يُحفظ التقدّم والملاحظات في هذا المتصفح على هذا الجهاز فقط. لا توجد حسابات.", conditionsTitle: "{organ}: حالات صحية مرتبطة", conditionsIntro: "لا تظهر هذه على شاشات طفلك، وهي هنا لتتحدثا عنها معًا إذا طُرحت.", partsKnown: "أجزاء الجسم التي تعرفها: {count} من {total}", practice: "وقت التدريب!", practiceCount: "أجزاء للتدريب: {count}", amazingFacts: "حقائق مدهشة", howItWorks: "كيف يعمل" },
    ar: { button: "شاهده في غرفتك", title: "{organ} في غرفتك", introWebxr: "وجّه الكاميرا إلى طاولة أو إلى الأرض، ثم انقر لتضع العضو: {organ}. تجوّل حوله لتراه من كل الجهات.", introQuickLook: "سيفتح جهازك العضو في عارض الواقع المعزز: {organ}. وجّهه إلى طاولة أو إلى الأرض لتضعه.", preparing: "جارٍ التجهيز: {organ}…", start: "ضعه في غرفتي", lifeSize: "الحجم الحقيقي: نحو {size} سم", enlarged: "مكبّر لتراه بشكل أوضح", unsupported: "افتح Anatomy Atelier على هاتف أو جهاز لوحي لتضع العضو في غرفتك: {organ}.", failed: "تعذّر بدء الواقع المعزز على هذا الجهاز. يمكنك متابعة استكشاف العضو هنا: {organ}.", placeHint: "حرّك هاتفك ببطء حتى ترى الحلقة، ثم انقر", placed: "انقر في مكان آخر لتحريكه", done: "تم", safety: "ابقَ في مكان آمن وانتبه إلى طريقك." },
    daily: { tab: "اليوم", title: "سؤال اليوم", whichOrgan: "ما هذا العضو؟", whichPart: "{organ}: ما هذا الجزء؟", correct: "نعم! إجابة صحيحة.", wrong: "محاولة جيدة! الإجابة: {answer}.", streakLabel: "أيام متتالية", streakStart: "أجب اليوم لتبدأ سلسلتك!", best: "الأفضل: {count}", comeBack: "عُد غدًا لسؤال جديد.", see3d: "شاهده ثلاثي الأبعاد", newQuestion: "سؤال جديد بانتظارك" },
  },
  pt: {
    systems: { title: "Sistemas do corpo", names: { cardiovascular: "Cardiovascular", nervous: "Nervoso", respiratory: "Respiratório", digestive: "Digestivo", urinary: "Urinário", sensory: "Sensorial", endocrine: "Endócrino", integumentary: "Tegumentar" } },
    saved: { title: "Órgãos salvos", empty: "Nenhum órgão salvo ainda. Use o marcador para guardar um aqui.", add: "Salvar este órgão", remove: "Remover dos salvos" },
    notes: { title: "Notas de estudo", placeholder: "Escreva o que quer lembrar sobre o {organ}…", status: "Salvo neste dispositivo" },
    search: { empty: "Nenhum órgão corresponde a “{query}”.", clear: "Limpar busca" },
    lesson: { step: "Etapa {current} de {total}", next: "Avançar", back: "Voltar", finish: "Concluir lição", overview: "Visão geral", structures: "Estruturas a localizar", clinical: "Importância clínica", sources: "Fontes", sourcesIntro: "Esta lição baseia-se nas referências a seguir." },
    related: { title: "Órgãos relacionados" },
    viewer: { error: "Não foi possível carregar o modelo do {organ}.", retry: "Tentar novamente", hint: "Use as setas para percorrer as estruturas.", previous: "Estrutura anterior", next: "Próxima estrutura" },
    quiz: { best: "Melhor: {score}/{total}", newBest: "Novo recorde pessoal!", mastery: "Domínio {percent}%", review: "Revisar", reviewCount: "{count} para revisar", modeIdentify: "Encontre", modeReverse: "Nomeie a estrutura destacada", modeDescribe: "Associe a descrição", reversePrompt: "O que está destacado?", optionsLabel: "Opções de resposta" },
    kids: { grownups: "Adultos", grownupsTitle: "Para adultos", grownupsIntro: "O Anatomy Atelier ajuda crianças curiosas a explorar o corpo. É uma ferramenta de aprendizagem, não aconselhamento médico — se você estiver preocupado com a saúde da criança, fale com um médico.", privacy: "O progresso e as notas ficam salvos apenas neste navegador, neste dispositivo. Não há contas.", conditionsTitle: "{organ}: problemas de saúde relacionados", conditionsIntro: "Eles não aparecem nas telas da criança. Estão aqui para que vocês possam conversar sobre eles juntos, se surgirem.", partsKnown: "Você conhece {count} de {total} partes do corpo", practice: "Hora de praticar!", practiceCount: "{count} partes do corpo para praticar", amazingFacts: "Fatos incríveis", howItWorks: "Como funciona" },
    ar: { button: "Veja na sua casa", title: "{organ} na sua casa", introWebxr: "Aponte a câmera para uma mesa ou o chão e toque para posicionar: {organ}. Ande em volta para ver de todos os lados.", introQuickLook: "Seu aparelho vai abrir {organ} no visualizador de RA. Aponte para uma mesa ou o chão.", preparing: "Preparando: {organ}…", start: "Colocar na minha casa", lifeSize: "Tamanho real: cerca de {size} cm", enlarged: "Ampliado para você ver melhor", unsupported: "Abra o Anatomy Atelier em um celular ou tablet para colocar {organ} na sua casa.", failed: "A RA não pôde começar neste aparelho. Você ainda pode explorar aqui: {organ}.", placeHint: "Mova o celular devagar até ver o anel e toque", placed: "Toque em outro lugar para mover o modelo", done: "Pronto", safety: "Fique num lugar seguro e olhe por onde anda." },
    daily: { tab: "Hoje", title: "Pergunta do dia", whichOrgan: "Que órgão é este?", whichPart: "{organ}: que parte é esta?", correct: "Isso! Acertou.", wrong: "Boa tentativa! É: {answer}.", streakLabel: "Sequência", streakStart: "Responda hoje para começar sua sequência!", best: "Recorde: {count}", comeBack: "Volte amanhã para uma nova pergunta.", see3d: "Ver em 3D", newQuestion: "Uma nova pergunta está esperando" },
  },
  fr: {
    systems: { title: "Systèmes du corps", names: { cardiovascular: "Cardiovasculaire", nervous: "Nerveux", respiratory: "Respiratoire", digestive: "Digestif", urinary: "Urinaire", sensory: "Sensoriel", endocrine: "Endocrinien", integumentary: "Tégumentaire" } },
    saved: { title: "Organes enregistrés", empty: "Aucun organe enregistré. Utilisez le signet pour en garder un ici.", add: "Enregistrer cet organe", remove: "Retirer des enregistrés" },
    notes: { title: "Notes d’étude", placeholder: "Notez ce que vous voulez retenir du {organ}…", status: "Enregistré sur cet appareil" },
    search: { empty: "Aucun organe ne correspond à « {query} ».", clear: "Effacer la recherche" },
    lesson: { step: "Étape {current} sur {total}", next: "Suivant", back: "Retour", finish: "Terminer la leçon", overview: "Aperçu", structures: "Structures à repérer", clinical: "Importance clinique", sources: "Sources", sourcesIntro: "Cette leçon s’appuie sur les références suivantes." },
    related: { title: "Organes liés" },
    viewer: { error: "Impossible de charger le modèle du {organ}.", retry: "Réessayer", hint: "Utilisez les flèches pour parcourir les structures.", previous: "Structure précédente", next: "Structure suivante" },
    quiz: { best: "Record : {score}/{total}", newBest: "Nouveau record personnel !", mastery: "Maîtrise {percent} %", review: "Réviser", reviewCount: "{count} à réviser", modeIdentify: "Trouvez", modeReverse: "Nommez la structure en surbrillance", modeDescribe: "Associez la description", reversePrompt: "Quelle structure est en surbrillance ?", optionsLabel: "Choix de réponse" },
    kids: { grownups: "Adultes", grownupsTitle: "Pour les adultes", grownupsIntro: "Anatomy Atelier aide les enfants curieux à explorer le corps. C’est un outil d’apprentissage, pas un avis médical : si la santé de votre enfant vous inquiète, parlez-en à un médecin.", privacy: "La progression et les notes sont enregistrées uniquement dans ce navigateur, sur cet appareil. Il n’y a pas de compte.", conditionsTitle: "{organ} : problèmes de santé associés", conditionsIntro: "Ils n’apparaissent pas sur les écrans de votre enfant. Ils sont ici pour que vous puissiez en parler ensemble si le sujet se présente.", partsKnown: "Tu connais {count} parties du corps sur {total}", practice: "C’est l’heure de s’entraîner !", practiceCount: "{count} parties du corps à revoir", amazingFacts: "Faits étonnants", howItWorks: "Comment ça marche" },
    ar: { button: "Voir chez toi", title: "{organ} chez toi", introWebxr: "Vise une table ou le sol avec la caméra, puis touche l’écran pour poser l’organe : {organ}. Tourne autour pour le voir sous tous les angles.", introQuickLook: "Ton appareil va ouvrir l’organe en réalité augmentée : {organ}. Vise une table ou le sol pour le poser.", preparing: "Préparation en cours : {organ}…", start: "Le poser chez moi", lifeSize: "Taille réelle : environ {size} cm", enlarged: "Agrandi pour mieux le voir", unsupported: "Ouvre Anatomy Atelier sur un téléphone ou une tablette pour poser l’organe chez toi : {organ}.", failed: "La réalité augmentée n’a pas pu démarrer sur cet appareil. Tu peux continuer à explorer ici : {organ}.", placeHint: "Bouge ton téléphone doucement jusqu’à voir l’anneau, puis touche", placed: "Touche ailleurs pour le déplacer", done: "Terminé", safety: "Reste dans un endroit sûr et regarde où tu marches." },
    daily: { tab: "Aujourd’hui", title: "Question du jour", whichOrgan: "Quel organe est-ce ?", whichPart: "{organ} : quelle partie est-ce ?", correct: "Oui ! Bonne réponse.", wrong: "Bien essayé ! C’est : {answer}.", streakLabel: "Série", streakStart: "Réponds aujourd’hui pour lancer ta série !", best: "Record : {count}", comeBack: "Reviens demain pour une nouvelle question.", see3d: "Voir en 3D", newQuestion: "Une nouvelle question t’attend" },
  },
  de: {
    systems: { title: "Körpersysteme", names: { cardiovascular: "Herz-Kreislauf", nervous: "Nerven", respiratory: "Atmung", digestive: "Verdauung", urinary: "Harn", sensory: "Sinne", endocrine: "Hormone", integumentary: "Haut" } },
    saved: { title: "Gemerkte Organe", empty: "Noch keine Organe gemerkt. Über das Lesezeichen hinzufügen.", add: "Organ merken", remove: "Aus Gemerkten entfernen" },
    notes: { title: "Lernnotizen", placeholder: "Notiere, was du dir zum {organ} merken willst…", status: "Auf diesem Gerät gespeichert" },
    search: { empty: "Kein Organ passt zu „{query}“.", clear: "Suche löschen" },
    lesson: { step: "Schritt {current} von {total}", next: "Weiter", back: "Zurück", finish: "Lektion beenden", overview: "Überblick", structures: "Zu findende Strukturen", clinical: "Klinische Bedeutung", sources: "Quellen", sourcesIntro: "Diese Lektion stützt sich auf die folgenden Quellen." },
    related: { title: "Verwandte Organe" },
    viewer: { error: "Das {organ}-Modell konnte nicht geladen werden.", retry: "Erneut versuchen", hint: "Mit den Pfeiltasten durch die Strukturen gehen.", previous: "Vorherige Struktur", next: "Nächste Struktur" },
    quiz: { best: "Bestwert: {score}/{total}", newBest: "Neue Bestleistung!", mastery: "Beherrschung {percent} %", review: "Wiederholen", reviewCount: "{count} zur Wiederholung", modeIdentify: "Finde", modeReverse: "Benenne die hervorgehobene Struktur", modeDescribe: "Ordne die Beschreibung zu", reversePrompt: "Welche Struktur ist hervorgehoben?", optionsLabel: "Antwortoptionen" },
    kids: { grownups: "Erwachsene", grownupsTitle: "Für Erwachsene", grownupsIntro: "Anatomy Atelier hilft neugierigen Kindern, den Körper zu entdecken. Es ist ein Lernwerkzeug, keine medizinische Beratung – wenn Sie sich um die Gesundheit Ihres Kindes sorgen, sprechen Sie mit einer Ärztin oder einem Arzt.", privacy: "Fortschritt und Notizen werden nur in diesem Browser auf diesem Gerät gespeichert. Es gibt keine Konten.", conditionsTitle: "{organ}: damit verbundene Erkrankungen", conditionsIntro: "Sie erscheinen nicht auf den Bildschirmen Ihres Kindes. Sie stehen hier, damit Sie gemeinsam darüber sprechen können, wenn das Thema aufkommt.", partsKnown: "Du kennst {count} von {total} Körperteilen", practice: "Zeit zum Üben!", practiceCount: "{count} Körperteile zum Üben", amazingFacts: "Erstaunliche Fakten", howItWorks: "So funktioniert es" },
    ar: { button: "In deinem Zimmer ansehen", title: "{organ} in deinem Zimmer", introWebxr: "Richte die Kamera auf einen Tisch oder den Boden und tippe, um das Organ abzustellen: {organ}. Geh drumherum, um es von allen Seiten zu sehen.", introQuickLook: "Dein Gerät öffnet das Organ in seinem AR-Viewer: {organ}. Richte es auf einen Tisch oder den Boden.", preparing: "Wird vorbereitet: {organ} …", start: "In mein Zimmer stellen", lifeSize: "Echte Größe: etwa {size} cm", enlarged: "Vergrößert, damit du es besser siehst", unsupported: "Öffne Anatomy Atelier auf einem Handy oder Tablet, um das Organ in dein Zimmer zu holen: {organ}.", failed: "AR konnte auf diesem Gerät nicht starten. Du kannst das Organ hier weiter erkunden: {organ}.", placeHint: "Beweg dein Handy langsam, bis du den Ring siehst, und tippe dann", placed: "Tippe woanders hin, um es zu verschieben", done: "Fertig", safety: "Bleib an einem sicheren Ort und pass auf, wohin du gehst." },
    daily: { tab: "Heute", title: "Frage des Tages", whichOrgan: "Welches Organ ist das?", whichPart: "{organ}: Welcher Teil ist das?", correct: "Ja! Richtig.", wrong: "Gut versucht! Es ist: {answer}.", streakLabel: "Serie", streakStart: "Antworte heute und starte deine Serie!", best: "Rekord: {count}", comeBack: "Komm morgen wieder für eine neue Frage.", see3d: "In 3D ansehen", newQuestion: "Eine neue Frage wartet" },
  },
  ja: {
    systems: { title: "からだの系統", names: { cardiovascular: "循環器系", nervous: "神経系", respiratory: "呼吸器系", digestive: "消化器系", urinary: "泌尿器系", sensory: "感覚器系", endocrine: "内分泌系", integumentary: "外皮系" } },
    saved: { title: "保存した臓器", empty: "まだ保存された臓器はありません。ブックマークから追加できます。", add: "この臓器を保存", remove: "保存から削除" },
    notes: { title: "学習メモ", placeholder: "{organ}について覚えておきたいことを書きましょう…", status: "この端末に保存しました" },
    search: { empty: "「{query}」に一致する臓器はありません。", clear: "検索をクリア" },
    lesson: { step: "ステップ {current} / {total}", next: "次へ", back: "戻る", finish: "レッスンを終了", overview: "概要", structures: "見つける構造", clinical: "臨床的な意義", sources: "出典", sourcesIntro: "このレッスンは以下の資料に基づいています。" },
    related: { title: "関連する臓器" },
    viewer: { error: "{organ}のモデルを読み込めませんでした。", retry: "再試行", hint: "矢印キーで構造を順に確認できます。", previous: "前の構造", next: "次の構造" },
    quiz: { best: "最高記録: {score}/{total}", newBest: "自己ベスト更新！", mastery: "習得度 {percent}%", review: "復習", reviewCount: "復習待ち {count} 件", modeIdentify: "見つける", modeReverse: "ハイライトされた構造の名前", modeDescribe: "説明に一致するもの", reversePrompt: "ハイライトされているのは？", optionsLabel: "回答の選択肢" },
    kids: { grownups: "保護者向け", grownupsTitle: "保護者の方へ", grownupsIntro: "Anatomy Atelier は、好奇心いっぱいの子どもたちがからだを探検するための学習ツールです。医療上のアドバイスではありません。お子さまの健康が心配なときは、医師にご相談ください。", privacy: "進み具合とメモは、この端末のこのブラウザにのみ保存されます。アカウントはありません。", conditionsTitle: "{organ}：関連する病気", conditionsIntro: "これらはお子さまの画面には表示されません。話題になったときに一緒に話し合えるよう、ここにまとめています。", partsKnown: "からだの部分 {total} 個のうち {count} 個を覚えたよ", practice: "練習の時間だよ！", practiceCount: "練習する部分：{count} 個", amazingFacts: "びっくり豆知識", howItWorks: "しくみ" },
    ar: { button: "へやに出してみよう", title: "へやの中の{organ}", introWebxr: "カメラをテーブルや床に向けて、タップすると{organ}を置けます。まわりを歩いて、いろいろな方向から見てみよう。", introQuickLook: "AR ビューアで{organ}が開きます。テーブルや床に向けて置いてみよう。", preparing: "{organ}を準備中…", start: "へやに置く", lifeSize: "実物大：約 {size} cm", enlarged: "見やすいように大きくしています", unsupported: "スマホやタブレットで Anatomy Atelier を開くと、{organ}をへやに置けます。", failed: "この端末では AR を始められませんでした。ここで{organ}を探検できます。", placeHint: "リングが見えるまでゆっくりスマホを動かして、タップしよう", placed: "別の場所をタップすると動かせます", done: "おわり", safety: "安全な場所で、足もとに気をつけてね。" },
    daily: { tab: "きょう", title: "きょうの問題", whichOrgan: "これはどの器官？", whichPart: "{organ}：これはどの部分？", correct: "せいかい！", wrong: "おしい！答えは「{answer}」。", streakLabel: "連続日数", streakStart: "きょう答えて、連続記録をスタートしよう！", best: "最高記録：{count}", comeBack: "あしたも新しい問題があるよ。", see3d: "3Dで見る", newQuestion: "新しい問題が待っているよ" },
  },
  ru: {
    systems: { title: "Системы организма", names: { cardiovascular: "Сердечно-сосудистая", nervous: "Нервная", respiratory: "Дыхательная", digestive: "Пищеварительная", urinary: "Мочевая", sensory: "Сенсорная", endocrine: "Эндокринная", integumentary: "Покровная" } },
    saved: { title: "Сохранённые органы", empty: "Пока нет сохранённых органов. Добавьте закладкой.", add: "Сохранить орган", remove: "Убрать из сохранённых" },
    notes: { title: "Учебные заметки", placeholder: "Запишите, что хотите запомнить об органе «{organ}»…", status: "Сохранено на этом устройстве" },
    search: { empty: "Нет органов по запросу «{query}».", clear: "Очистить поиск" },
    lesson: { step: "Шаг {current} из {total}", next: "Далее", back: "Назад", finish: "Завершить урок", overview: "Обзор", structures: "Структуры для поиска", clinical: "Клиническое значение", sources: "Источники", sourcesIntro: "Урок опирается на следующие источники." },
    related: { title: "Связанные органы" },
    viewer: { error: "Не удалось загрузить модель: {organ}.", retry: "Повторить", hint: "Используйте стрелки для перехода между структурами.", previous: "Предыдущая структура", next: "Следующая структура" },
    quiz: { best: "Лучший результат: {score}/{total}", newBest: "Новый личный рекорд!", mastery: "Освоено {percent}%", review: "Повторить", reviewCount: "{count} к повторению", modeIdentify: "Найдите", modeReverse: "Назовите выделенную структуру", modeDescribe: "Сопоставьте описание", reversePrompt: "Что выделено?", optionsLabel: "Варианты ответа" },
    kids: { grownups: "Взрослым", grownupsTitle: "Для взрослых", grownupsIntro: "Anatomy Atelier помогает любознательным детям изучать тело. Это учебный инструмент, а не медицинская консультация: если вас беспокоит здоровье ребёнка, обратитесь к врачу.", privacy: "Прогресс и заметки сохраняются только в этом браузере на этом устройстве. Учётных записей нет.", conditionsTitle: "{organ}: связанные заболевания", conditionsIntro: "Они не показываются на экранах ребёнка. Они собраны здесь, чтобы вы могли обсудить их вместе, если зайдёт речь.", partsKnown: "Частей тела изучено: {count} из {total}", practice: "Время тренировки!", practiceCount: "Частей тела для тренировки: {count}", amazingFacts: "Удивительные факты", howItWorks: "Как это работает" },
    ar: { button: "Посмотреть у себя в комнате", title: "{organ} у тебя в комнате", introWebxr: "Наведи камеру на стол или пол и нажми, чтобы поставить орган: {organ}. Обойди его, чтобы рассмотреть со всех сторон.", introQuickLook: "Устройство откроет орган в режиме дополненной реальности: {organ}. Наведи камеру на стол или пол.", preparing: "Готовим: {organ}…", start: "Поставить в комнате", lifeSize: "Настоящий размер: около {size} см", enlarged: "Увеличено, чтобы лучше рассмотреть", unsupported: "Открой Anatomy Atelier на телефоне или планшете, чтобы поставить орган у себя: {organ}.", failed: "Не удалось запустить AR на этом устройстве. Можно дальше изучать здесь: {organ}.", placeHint: "Медленно води телефоном, пока не увидишь кольцо, затем нажми", placed: "Нажми в другом месте, чтобы переставить", done: "Готово", safety: "Стой в безопасном месте и смотри, куда идёшь." },
    daily: { tab: "Сегодня", title: "Вопрос дня", whichOrgan: "Какой это орган?", whichPart: "{organ}: какая это часть?", correct: "Да! Правильно.", wrong: "Хорошая попытка! Правильный ответ: {answer}.", streakLabel: "Серия", streakStart: "Ответь сегодня и начни серию!", best: "Рекорд: {count}", comeBack: "Возвращайся завтра за новым вопросом.", see3d: "Посмотреть в 3D", newQuestion: "Тебя ждёт новый вопрос" },
  },
  id: {
    systems: { title: "Sistem tubuh", names: { cardiovascular: "Kardiovaskular", nervous: "Saraf", respiratory: "Pernapasan", digestive: "Pencernaan", urinary: "Kemih", sensory: "Sensorik", endocrine: "Endokrin", integumentary: "Integumen" } },
    saved: { title: "Organ tersimpan", empty: "Belum ada organ tersimpan. Gunakan penanda untuk menyimpannya.", add: "Simpan organ ini", remove: "Hapus dari tersimpan" },
    notes: { title: "Catatan belajar", placeholder: "Tulis hal yang ingin kamu ingat tentang {organ}…", status: "Tersimpan di perangkat ini" },
    search: { empty: "Tidak ada organ yang cocok dengan “{query}”.", clear: "Hapus pencarian" },
    lesson: { step: "Langkah {current} dari {total}", next: "Lanjut", back: "Kembali", finish: "Selesaikan pelajaran", overview: "Ringkasan", structures: "Struktur yang dicari", clinical: "Makna klinis", sources: "Sumber", sourcesIntro: "Pelajaran ini merujuk pada sumber berikut." },
    related: { title: "Organ terkait" },
    viewer: { error: "Model {organ} gagal dimuat.", retry: "Coba lagi", hint: "Gunakan tombol panah untuk menelusuri struktur.", previous: "Struktur sebelumnya", next: "Struktur berikutnya" },
    quiz: { best: "Terbaik: {score}/{total}", newBest: "Rekor pribadi baru!", mastery: "Penguasaan {percent}%", review: "Ulangi", reviewCount: "{count} perlu diulang", modeIdentify: "Temukan", modeReverse: "Sebutkan struktur yang disorot", modeDescribe: "Cocokkan deskripsi", reversePrompt: "Struktur apa yang disorot?", optionsLabel: "Pilihan jawaban" },
    kids: { grownups: "Orang tua", grownupsTitle: "Untuk orang tua", grownupsIntro: "Anatomy Atelier membantu anak-anak yang penasaran menjelajahi tubuh. Ini alat belajar, bukan nasihat medis — jika Anda khawatir tentang kesehatan anak, bicarakan dengan dokter.", privacy: "Kemajuan dan catatan hanya disimpan di browser ini, di perangkat ini. Tidak ada akun.", conditionsTitle: "{organ}: masalah kesehatan terkait", conditionsIntro: "Ini tidak ditampilkan di layar anak. Daftar ini ada di sini agar Anda bisa membicarakannya bersama jika topiknya muncul.", partsKnown: "Kamu tahu {count} dari {total} bagian tubuh", practice: "Waktunya berlatih!", practiceCount: "{count} bagian tubuh untuk dilatih", amazingFacts: "Fakta menakjubkan", howItWorks: "Cara kerjanya" },
    ar: { button: "Lihat di kamarmu", title: "{organ} di kamarmu", introWebxr: "Arahkan kamera ke meja atau lantai, lalu ketuk untuk menaruh {organ}. Berjalanlah mengelilinginya untuk melihat dari semua sisi.", introQuickLook: "Perangkatmu akan membuka {organ} di penampil AR. Arahkan ke meja atau lantai untuk menaruhnya.", preparing: "Menyiapkan {organ}…", start: "Taruh di kamarku", lifeSize: "Ukuran asli: sekitar {size} cm", enlarged: "Diperbesar agar lebih jelas", unsupported: "Buka Anatomy Atelier di ponsel atau tablet untuk menaruh {organ} di kamarmu.", failed: "AR tidak bisa dimulai di perangkat ini. Kamu tetap bisa menjelajahi {organ} di sini.", placeHint: "Gerakkan ponselmu pelan-pelan sampai cincin muncul, lalu ketuk", placed: "Ketuk tempat lain untuk memindahkannya", done: "Selesai", safety: "Tetap di tempat yang aman dan perhatikan langkahmu." },
    daily: { tab: "Hari ini", title: "Pertanyaan hari ini", whichOrgan: "Organ apakah ini?", whichPart: "{organ}: bagian apakah ini?", correct: "Ya! Benar.", wrong: "Usaha yang bagus! Jawabannya: {answer}.", streakLabel: "Hari beruntun", streakStart: "Jawab hari ini untuk memulai rentetanmu!", best: "Rekor: {count}", comeBack: "Kembali besok untuk pertanyaan baru.", see3d: "Lihat dalam 3D", newQuestion: "Ada pertanyaan baru menunggumu" },
  },
  ko: {
    systems: { title: "인체 계통", names: { cardiovascular: "순환계", nervous: "신경계", respiratory: "호흡계", digestive: "소화계", urinary: "비뇨계", sensory: "감각계", endocrine: "내분비계", integumentary: "외피계" } },
    saved: { title: "저장한 장기", empty: "저장한 장기가 없습니다. 북마크로 추가해 보세요.", add: "이 장기 저장", remove: "저장 해제" },
    notes: { title: "학습 노트", placeholder: "{organ}에 대해 기억하고 싶은 내용을 적어 보세요…", status: "이 기기에 저장됨" },
    search: { empty: "“{query}”과(와) 일치하는 장기가 없습니다.", clear: "검색 지우기" },
    lesson: { step: "{total}단계 중 {current}단계", next: "다음", back: "이전", finish: "레슨 마치기", overview: "개요", structures: "찾아볼 구조", clinical: "임상적 의의", sources: "출처", sourcesIntro: "이 레슨은 다음 자료를 참고했습니다." },
    related: { title: "관련 장기" },
    viewer: { error: "{organ} 모델을 불러오지 못했습니다.", retry: "다시 시도", hint: "화살표 키로 구조를 차례로 살펴보세요.", previous: "이전 구조", next: "다음 구조" },
    quiz: { best: "최고 기록: {score}/{total}", newBest: "개인 최고 기록!", mastery: "숙달도 {percent}%", review: "복습", reviewCount: "복습 {count}개", modeIdentify: "찾기", modeReverse: "강조된 구조 이름", modeDescribe: "설명과 일치시키기", reversePrompt: "강조된 구조는 무엇인가요?", optionsLabel: "답변 선택지" },
    kids: { grownups: "보호자", grownupsTitle: "보호자를 위한 안내", grownupsIntro: "Anatomy Atelier는 호기심 많은 아이들이 몸을 탐험하도록 돕는 학습 도구입니다. 의학적 조언이 아니며, 아이의 건강이 걱정된다면 의사와 상담하세요.", privacy: "학습 기록과 메모는 이 기기의 이 브라우저에만 저장됩니다. 계정은 없습니다.", conditionsTitle: "{organ}: 관련 질환", conditionsIntro: "이 내용은 아이의 화면에는 나오지 않습니다. 이야기가 나왔을 때 함께 대화할 수 있도록 여기에 모아 두었습니다.", partsKnown: "몸의 부분 {total}개 중 {count}개를 알아요", practice: "연습할 시간이에요!", practiceCount: "연습할 부분 {count}개", amazingFacts: "놀라운 사실", howItWorks: "이렇게 일해요" },
    ar: { button: "내 방에서 보기", title: "내 방 안의 {organ}", introWebxr: "카메라를 탁자나 바닥에 비추고 탭하면 {organ}을(를) 놓을 수 있어요. 주위를 돌면서 여러 방향에서 봐요.", introQuickLook: "기기의 AR 뷰어에서 {organ}이(가) 열려요. 탁자나 바닥에 비춰서 놓아 봐요.", preparing: "{organ} 준비 중…", start: "내 방에 놓기", lifeSize: "실제 크기: 약 {size}cm", enlarged: "잘 보이도록 크게 보여 줘요", unsupported: "휴대폰이나 태블릿에서 Anatomy Atelier를 열면 {organ}을(를) 내 방에 놓을 수 있어요.", failed: "이 기기에서는 AR을 시작할 수 없어요. 여기에서 계속 {organ}을(를) 탐험할 수 있어요.", placeHint: "고리가 보일 때까지 휴대폰을 천천히 움직인 다음 탭해요", placed: "다른 곳을 탭하면 옮길 수 있어요", done: "완료", safety: "안전한 곳에서 발밑을 잘 살펴요." },
    daily: { tab: "오늘", title: "오늘의 질문", whichOrgan: "이건 어떤 장기일까요?", whichPart: "{organ}: 이건 어느 부분일까요?", correct: "맞아요! 정답이에요.", wrong: "좋은 시도예요! 정답: {answer}", streakLabel: "연속 일수", streakStart: "오늘 답하고 연속 기록을 시작해요!", best: "최고 기록: {count}", comeBack: "내일 새로운 질문으로 다시 만나요.", see3d: "3D로 보기", newQuestion: "새 질문이 기다리고 있어요" },
  },
};
